deps = "sha256-R5GEtQAdIL1nq1Y/5bVO1FsHmjol2vscak5hRSdYY+U="
cargo_config = '''
[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/hannes-hochreiner/exec-rs?tag=v2.0.1"]
git = "https://github.com/hannes-hochreiner/exec-rs"
tag = "v2.0.1"
replace-with = "vendored-sources"

[source."git+https://github.com/hannes-hochreiner/policer?tag=v0.3.3"]
git = "https://github.com/hannes-hochreiner/policer"
tag = "v0.3.3"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/tmp/backup_btrfs_deps_723bb129-08c7-4cf6-af5a-d4cbcf6cc2bc"'''
cargo_lock = "9e6bec4a029d9da5f67f461ca017185d01d55aad0580655660b379fc61a7ffe1"
